name: Documentation

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:
  generate-docs:
    name: Generate and Deploy Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Generate documentation
        run: ./gradlew dokkaAllLibraries --no-daemon --stacktrace

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dokka/multimodule
          #cname: biometricauth-docs.com

      - name: Generate documentation summary
        run: |
          echo "📚 Documentation generated and deployed successfully!"
          echo "Available at: website"
          echo "Commit: ${{ github.sha }}"

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: ./build/dokka/multimodule
          retention-days: 30