name: Documentation

on:
  workflow_call:

concurrency:
  group: '${{ github.workflow }}-${{ github.actor }}'
  cancel-in-progress: true

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs=-Xmx8192M -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options=-Xmx8192M

jobs:
  generate-docs:
    name: Generate and Deploy Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-cache-${{ runner.os }}-

      - name: Restore Kotlin/Native cache
        uses: actions/cache@v3
        with:
          path: ~/.konan/cache
          key: kotlin-native-cache-${{ runner.os }}-${{ hashFiles('**/*.kt', '**/*.kts', '**/*.def') }}
          restore-keys: kotlin-native-cache-${{ runner.os }}-



      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2

      - name: Generate documentation
        run: ./gradlew dokkaAllLibraries --no-daemon --stacktrace

      - name: Save Kotlin/Native cache
        if: ${{ always() }}
        uses: actions/cache@v3
        with:
          path: ~/.konan/cache
          key: kotlin-native-cache-${{ runner.os }}-${{ hashFiles('**/*.kt', '**/*.kts', '**/*.def') }}


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dokka/multimodule


      - name: Generate documentation summary
        run: |
          echo "📚 Documentation generated and deployed successfully!"
          echo "Available at: "
          echo "Commit: ${{ github.sha }}"

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: ./build/dokka/multimodule
          retention-days: 30