name: Biometric KMP Library CI/CD

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:
  validate:
    uses: ./.github/workflows/validate.yml

  test:
    needs: validate
    uses: ./.github/workflows/test.yml

  build:
    needs: validate
    uses: ./.github/workflows/build.yml

  publish-snapshot:
    needs: [test, build]
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    uses: ./.github/workflows/publish-snapshot.yml
    secrets: inherit

  publish-release:
    needs: [test, build]
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/publish-release.yml
    secrets: inherit

  documentation:
    needs: [test, build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/documentation.yml
    secrets: inherit