name: Manual CI

on:
  workflow_dispatch:
    inputs:
      test-matrix:
        description: 'Test matrix (ex: ubuntu-latest,macos-latest,windows-latest)'
        required: false
        default: 'ubuntu-latest,macos-latest'
      cache-read-only:
        description: 'Use read-only cache'
        type: boolean
        default: false

concurrency:
  group: '${{ github.workflow }}-${{ github.actor }}'
  cancel-in-progress: true

jobs:
  manual-ci:
    name: Manual CI Run
    uses: ./.github/workflows/ci-pipeline.yml
    with:
      cache-read-only: ${{ inputs.cache-read-only }}
    secrets: inherit
