name: Manual Documentation

on:
  workflow_dispatch:
    inputs:
      deploy-to-pages:
        description: 'Deploy to GitHub Pages'
        type: boolean
        default: true

concurrency:
  group: '${{ github.workflow }}-${{ github.actor }}'
  cancel-in-progress: true

jobs:
  generate-docs:
    name: Generate Documentation
    uses: ./.github/workflows/documentation.yml
    secrets: inherit