name: Publish Snapshot

on:
  workflow_call:

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:
  publish-snapshot:
    name: Publish Snapshot
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Set snapshot version
        run: |
          # Update version to include -SNAPSHOT suffix
          sed -i.bak 's/version = "\([^"]*\)"/version = "\1-SNAPSHOT"/' build.gradle.kts

      - name: Create local.properties
        run: |
          echo "mavenCentralUsername=${{ secrets.MAVEN_CENTRAL_USERNAME }}" >> local.properties
          echo "mavenCentralPassword=${{ secrets.MAVEN_CENTRAL_PASSWORD }}" >> local.properties
          echo "gpgKeySecret=${{ secrets.GPG_KEY_SECRET }}" >> local.properties
          echo "gpgKeyPassword=${{ secrets.GPG_KEY_PASSWORD }}" >> local.properties

      - name: Publish snapshot to Maven Central
        run: ./gradlew publishAllPublicationsToMavenCentral --no-daemon --no-configuration-cache --stacktrace

      - name: Clean up
        if: always()
        run: rm -f local.properties