name: Test

on:
  workflow_call:

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Run JVM tests
        run: ./gradlew jvmTest --no-daemon --stacktrace

      - name: Run Android tests (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew testDebugUnitTest --no-daemon --stacktrace

      - name: Run iOS tests (macOS only)
        if: matrix.os == 'macos-latest'
        run: ./gradlew iosSimulatorArm64Test --no-daemon --stacktrace

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.os }}
          path: |
            **/build/test-results/*/
            **/build/reports/tests/*/
          retention-days: 30